Fix syntax errors

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -22,35 +22,35 @@ jobs:
           test -f setup.py && pip install -e ".[dev]"
 
       - name: Check we are starting with clean git checkout
-          run: |
-            if [[ `git status --porcelain -uno` ]]; then
-              git diff
-              echo "git status is not clean"
-              false
-            fi
+        run: |
+          if [[ `git status --porcelain -uno` ]]; then
+            git diff
+            echo "git status is not clean"
+            false
+          fi
 
       - name: Trying to strip out notebooks
-          run: |
-            nbdev_clean
-            git status -s # display the status to see which nbs need cleaning up
-            if [[ `git status --porcelain -uno` ]]; then
-              git status -uno
-              echo -e "!!! Detected unstripped out notebooks\n!!!Remember to run nbdev_install_hooks"
-              echo -e "This error can also happen if you are using an older version of nbdev relative to what is in CI.  Please try to upgrade nbdev with the command `pip install -U nbdev`"
-              false
-            fi
+        run: |
+          nbdev_clean
+          git status -s # display the status to see which nbs need cleaning up
+          if [[ `git status --porcelain -uno` ]]; then
+            git status -uno
+            echo -e "!!! Detected unstripped out notebooks\n!!!Remember to run nbdev_install_hooks"
+            echo -e "This error can also happen if you are using an older version of nbdev relative to what is in CI.  Please try to upgrade nbdev with the command `pip install -U nbdev`"
+            false
+          fi
 
       - name: Do nbdev_export
-          run: |
-            nbdev_export
-            if [[ `git status --porcelain -uno` ]]; then
-              echo "::error::Notebooks and library are not in sync.  Please run nbdev_export."
-              git status -uno
-              git diff
-              exit 1;
-            fi
+        run: |
+          nbdev_export
+          if [[ `git status --porcelain -uno` ]]; then
+            echo "::error::Notebooks and library are not in sync.  Please run nbdev_export."
+            git status -uno
+            git diff
+            exit 1;
+          fi
 
       - name: Do  nbdev_test
-          run: |
-            nbdev_test
+        run: |
+          nbdev_test
 
